export interface ComponentEventMetadata {
  readonly name: string;
  readonly type: string;
}

export interface ComponentMetadata {
  readonly className: `Rg${string}Element`;
  readonly tag: `rg-${string}`;
  readonly family:
    'foundation' | 'action' | 'form' | 'display' | 'feedback' | 'navigation' | 'overlay';
  readonly summary: string;
  readonly attributes: readonly string[];
  readonly events?: readonly ComponentEventMetadata[];
  readonly slots?: readonly string[];
  readonly parts?: readonly string[];
}

const nativeValueEvents = [
  { name: 'input', type: 'Event' },
  { name: 'change', type: 'Event' },
] as const;

export const componentMetadata = [
  {
    className: 'RgThemeElement',
    tag: 'rg-theme',
    family: 'foundation',
    summary: 'Provides color, density, and motion context.',
    attributes: ['mode', 'density', 'motion'],
    events: [{ name: 'rg-theme-change', type: 'CustomEvent<RgThemeChangeDetail>' }],
    slots: ['default'],
    parts: ['root'],
  },
  {
    className: 'RgButtonElement',
    tag: 'rg-button',
    family: 'action',
    summary: 'Primary action control with kinetic press feedback.',
    attributes: [
      'aria-describedby',
      'aria-label',
      'aria-labelledby',
      'disabled',
      'full-width',
      'formnovalidate',
      'label',
      'loading',
      'name',
      'pressed',
      'size',
      'title',
      'tone',
      'type',
      'value',
      'variant',
    ],
    events: [{ name: 'rg-press', type: 'CustomEvent<RgPressDetail>' }],
    slots: ['start', 'default', 'end'],
    parts: ['base', 'control', 'button', 'spinner', 'start', 'label', 'icon', 'end'],
  },
  {
    className: 'RgIconButtonElement',
    tag: 'rg-icon-button',
    family: 'action',
    summary: 'Compact, accessible icon-only action.',
    attributes: [
      'aria-describedby',
      'aria-label',
      'aria-labelledby',
      'disabled',
      'full-width',
      'formnovalidate',
      'label',
      'loading',
      'name',
      'pressed',
      'size',
      'title',
      'tone',
      'type',
      'value',
      'variant',
    ],
    events: [{ name: 'rg-press', type: 'CustomEvent<RgPressDetail>' }],
    slots: ['start', 'default', 'end'],
    parts: ['base', 'control', 'button', 'spinner', 'start', 'label', 'icon', 'end'],
  },
  {
    className: 'RgLinkElement',
    tag: 'rg-link',
    family: 'action',
    summary: 'Navigation action backed by a native anchor.',
    attributes: [
      'aria-current',
      'aria-describedby',
      'aria-label',
      'aria-labelledby',
      'disabled',
      'download',
      'external',
      'href',
      'hreflang',
      'referrerpolicy',
      'rel',
      'size',
      'target',
      'title',
      'tone',
      'type',
      'variant',
    ],
    events: [{ name: 'rg-navigate', type: 'CustomEvent<RgNavigateDetail>' }],
    slots: ['start', 'default', 'end'],
    parts: ['base', 'link', 'control', 'start', 'label', 'end', 'external-icon'],
  },
  {
    className: 'RgInputElement',
    tag: 'rg-input',
    family: 'form',
    summary: 'Form-associated single-line text input.',
    attributes: [
      'autocomplete',
      'clearable',
      'description',
      'disabled',
      'error',
      'inputmode',
      'invalid',
      'label',
      'max',
      'maxlength',
      'min',
      'minlength',
      'name',
      'pattern',
      'placeholder',
      'readonly',
      'required',
      'size',
      'step',
      'type',
      'value',
    ],
    events: [
      ...nativeValueEvents,
      { name: 'rg-clear', type: 'CustomEvent<{ previousValue: string }>' },
    ],
    slots: ['label', 'start', 'end', 'description', 'error'],
    parts: [
      'field',
      'label-row',
      'label',
      'control-wrap',
      'start',
      'control',
      'input',
      'clear',
      'end',
      'description',
      'error',
    ],
  },
  {
    className: 'RgTextareaElement',
    tag: 'rg-textarea',
    family: 'form',
    summary: 'Form-associated multiline text input.',
    attributes: [
      'auto-grow',
      'cols',
      'description',
      'disabled',
      'error',
      'invalid',
      'label',
      'maxlength',
      'minlength',
      'name',
      'placeholder',
      'readonly',
      'required',
      'resize',
      'rows',
      'size',
      'value',
    ],
    events: nativeValueEvents,
    slots: ['label', 'description', 'error'],
    parts: [
      'field',
      'label-row',
      'label',
      'control-wrap',
      'control',
      'textarea',
      'description',
      'error',
    ],
  },
  {
    className: 'RgSelectElement',
    tag: 'rg-select',
    family: 'form',
    summary: 'Form-associated native select with declarative options.',
    attributes: [
      'description',
      'disabled',
      'error',
      'invalid',
      'label',
      'name',
      'placeholder',
      'required',
      'size',
      'value',
    ],
    events: nativeValueEvents,
    slots: ['label', 'description', 'error', 'default'],
    parts: [
      'field',
      'label-row',
      'label',
      'control-wrap',
      'control',
      'select',
      'icon',
      'description',
      'error',
    ],
  },
  {
    className: 'RgOptionElement',
    tag: 'rg-option',
    family: 'form',
    summary: 'Declarative option metadata for rg-select.',
    attributes: ['value', 'label', 'disabled', 'selected'],
    slots: ['default'],
    parts: [],
  },
  {
    className: 'RgCheckboxElement',
    tag: 'rg-checkbox',
    family: 'form',
    summary: 'Form-associated binary or indeterminate choice.',
    attributes: [
      'checked',
      'description',
      'disabled',
      'error',
      'indeterminate',
      'invalid',
      'label',
      'name',
      'required',
      'value',
    ],
    events: nativeValueEvents,
    slots: ['label', 'default', 'description', 'error'],
    parts: ['field', 'base', 'control', 'indicator', 'label', 'description', 'error'],
  },
  {
    className: 'RgSwitchElement',
    tag: 'rg-switch',
    family: 'form',
    summary: 'Form-associated on/off setting.',
    attributes: [
      'checked',
      'description',
      'disabled',
      'error',
      'invalid',
      'label',
      'name',
      'required',
      'value',
    ],
    events: nativeValueEvents,
    slots: ['label', 'default', 'description', 'error'],
    parts: ['field', 'base', 'control', 'track', 'thumb', 'label', 'description', 'error'],
  },
  {
    className: 'RgRadioGroupElement',
    tag: 'rg-radio-group',
    family: 'form',
    summary: 'Keyboard-navigable form-associated radio group.',
    attributes: [
      'description',
      'disabled',
      'error',
      'invalid',
      'label',
      'name',
      'orientation',
      'required',
      'value',
    ],
    events: nativeValueEvents,
    slots: ['label', 'default', 'description', 'error'],
    parts: ['group', 'label-row', 'label', 'options', 'description', 'error'],
  },
  {
    className: 'RgRadioElement',
    tag: 'rg-radio',
    family: 'form',
    summary: 'Radio option owned by rg-radio-group.',
    attributes: ['value', 'checked', 'disabled', 'label', 'description'],
    events: nativeValueEvents,
    slots: ['default', 'description'],
    parts: ['base', 'control', 'indicator', 'label', 'description'],
  },
  {
    className: 'RgSliderElement',
    tag: 'rg-slider',
    family: 'form',
    summary: 'Form-associated numeric range input.',
    attributes: [
      'description',
      'disabled',
      'error',
      'invalid',
      'label',
      'max',
      'min',
      'name',
      'orientation',
      'required',
      'show-value',
      'size',
      'step',
      'value',
    ],
    events: nativeValueEvents,
    slots: ['label', 'description', 'error'],
    parts: [
      'field',
      'label-row',
      'label',
      'value',
      'control',
      'track',
      'range',
      'description',
      'error',
    ],
  },
  {
    className: 'RgBadgeElement',
    tag: 'rg-badge',
    family: 'display',
    summary: 'Compact status or category label.',
    attributes: ['tone', 'variant', 'size', 'dot', 'removable', 'remove-label'],
    events: [{ name: 'rg-remove', type: 'CustomEvent<RgBadgeRemoveDetail>' }],
    slots: ['start', 'default', 'end'],
    parts: ['base', 'badge', 'dot', 'start', 'label', 'end', 'remove'],
  },
  {
    className: 'RgAvatarElement',
    tag: 'rg-avatar',
    family: 'display',
    summary: 'Image avatar with initials fallback and optional presence status.',
    attributes: [
      'alt',
      'crossorigin',
      'decoding',
      'initials',
      'loading',
      'name',
      'referrerpolicy',
      'shape',
      'size',
      'sizes',
      'src',
      'srcset',
      'status',
      'status-label',
    ],
    events: [
      { name: 'rg-load', type: 'CustomEvent<RgAvatarLoadDetail>' },
      { name: 'rg-error', type: 'CustomEvent<RgAvatarErrorDetail>' },
    ],
    slots: ['fallback', 'status'],
    parts: ['base', 'avatar', 'image', 'fallback', 'initials', 'status'],
  },
  {
    className: 'RgCardElement',
    tag: 'rg-card',
    family: 'display',
    summary: 'Content surface with optional media, header, and footer regions.',
    attributes: [
      'aria-describedby',
      'aria-label',
      'aria-labelledby',
      'variant',
      'padding',
      'radius',
      'lift',
    ],
    slots: ['media', 'header', 'default', 'footer'],
    parts: ['base', 'card', 'media', 'header', 'body', 'footer'],
  },
  {
    className: 'RgDividerElement',
    tag: 'rg-divider',
    family: 'display',
    summary: 'Horizontal or vertical content separator.',
    attributes: [
      'aria-label',
      'aria-labelledby',
      'decorative',
      'inset',
      'orientation',
      'spacing',
      'variant',
    ],
    slots: ['default'],
    parts: ['base', 'divider', 'line', 'rule', 'rule-before', 'label', 'rule-after'],
  },
  {
    className: 'RgAlertElement',
    tag: 'rg-alert',
    family: 'feedback',
    summary: 'Persistent contextual feedback.',
    attributes: ['tone', 'variant', 'dismissible', 'dismiss-label'],
    events: [{ name: 'rg-dismiss', type: 'CustomEvent<AlertDismissDetail>' }],
    slots: ['icon', 'title', 'default', 'actions'],
    parts: ['base', 'icon', 'content', 'title', 'message', 'actions', 'close'],
  },
  {
    className: 'RgProgressElement',
    tag: 'rg-progress',
    family: 'feedback',
    summary: 'Determinate or indeterminate task progress.',
    attributes: ['aria-label', 'value', 'max', 'label'],
    slots: ['label'],
    parts: ['base', 'meta', 'label', 'value', 'track', 'indicator'],
  },
  {
    className: 'RgMeterElement',
    tag: 'rg-meter',
    family: 'feedback',
    summary: 'Displays a scalar measurement within a known range.',
    attributes: [
      'aria-label',
      'high',
      'label',
      'low',
      'max',
      'min',
      'optimum',
      'show-value',
      'size',
      'tone',
      'value',
      'value-text',
    ],
    slots: ['label'],
    parts: ['base', 'meta', 'label', 'value', 'meter', 'track', 'indicator'],
  },
  {
    className: 'RgSpinnerElement',
    tag: 'rg-spinner',
    family: 'feedback',
    summary: 'Compact indeterminate busy indicator.',
    attributes: ['size', 'label'],
    slots: [],
    parts: ['base', 'indicator'],
  },
  {
    className: 'RgSkeletonElement',
    tag: 'rg-skeleton',
    family: 'feedback',
    summary: 'Placeholder for pending content.',
    attributes: ['shape', 'width', 'height', 'animated'],
    slots: [],
    parts: ['base'],
  },
  {
    className: 'RgToastRegionElement',
    tag: 'rg-toast-region',
    family: 'feedback',
    summary: 'Accessible live region and toast viewport.',
    attributes: ['position', 'max-visible', 'label', 'pause-on-hover'],
    events: [{ name: 'rg-toast-add', type: 'CustomEvent<{ id: string; toast: RgToastElement }>' }],
    slots: ['default'],
    parts: ['viewport'],
  },
  {
    className: 'RgToastElement',
    tag: 'rg-toast',
    family: 'feedback',
    summary: 'Temporary status notification.',
    attributes: ['open', 'tone', 'duration', 'dismissible', 'dismiss-label'],
    events: [
      { name: 'rg-open-change', type: 'CustomEvent<ToastOpenChangeDetail>' },
      { name: 'rg-dismiss', type: 'CustomEvent<ToastDismissDetail>' },
    ],
    slots: ['icon', 'title', 'default', 'action'],
    parts: [
      'base',
      'accent',
      'layout',
      'icon',
      'content',
      'title',
      'message',
      'action',
      'close',
      'progress',
    ],
  },
  {
    className: 'RgTabsElement',
    tag: 'rg-tabs',
    family: 'navigation',
    summary: 'Roving-tabindex tab set.',
    attributes: ['value', 'orientation', 'activation', 'loop'],
    events: [{ name: 'rg-value-change', type: 'CustomEvent<TabsValueChangeDetail>' }],
    slots: ['tab', 'default'],
    parts: ['base', 'tablist', 'indicator', 'panels'],
  },
  {
    className: 'RgTabElement',
    tag: 'rg-tab',
    family: 'navigation',
    summary: 'Interactive tab owned by rg-tabs.',
    attributes: ['aria-label', 'aria-labelledby', 'value', 'selected', 'disabled'],
    slots: ['default'],
    parts: ['base', 'label'],
  },
  {
    className: 'RgTabPanelElement',
    tag: 'rg-tab-panel',
    family: 'navigation',
    summary: 'Content panel owned by rg-tabs.',
    attributes: ['value', 'active'],
    slots: ['default'],
    parts: ['base'],
  },
  {
    className: 'RgAccordionElement',
    tag: 'rg-accordion',
    family: 'navigation',
    summary: 'Single or multiple disclosure group.',
    attributes: ['value', 'multiple', 'collapsible'],
    events: [{ name: 'rg-value-change', type: 'CustomEvent<AccordionValueChangeDetail>' }],
    slots: ['default'],
    parts: ['base'],
  },
  {
    className: 'RgAccordionItemElement',
    tag: 'rg-accordion-item',
    family: 'navigation',
    summary: 'Native-details disclosure item.',
    attributes: ['value', 'open', 'disabled', 'heading-level'],
    events: [{ name: 'rg-open-change', type: 'CustomEvent<AccordionItemOpenChangeDetail>' }],
    slots: ['heading', 'default'],
    parts: ['base', 'trigger', 'heading', 'icon', 'panel', 'content'],
  },
  {
    className: 'RgDialogElement',
    tag: 'rg-dialog',
    family: 'overlay',
    summary: 'Modal surface backed by native dialog.',
    attributes: [
      'open',
      'size',
      'label',
      'escape-key-action',
      'backdrop-action',
      'hide-close',
      'close-label',
    ],
    events: [
      { name: 'rg-before-close', type: 'CustomEvent<DialogBeforeCloseDetail>' },
      { name: 'rg-open-change', type: 'CustomEvent<DialogOpenChangeDetail>' },
      { name: 'rg-close', type: 'CustomEvent<DialogCloseDetail>' },
    ],
    slots: ['trigger', 'title', 'close', 'default', 'footer'],
    parts: ['trigger', 'base', 'dialog', 'panel', 'header', 'title', 'close', 'body', 'footer'],
  },
  {
    className: 'RgDrawerElement',
    tag: 'rg-drawer',
    family: 'overlay',
    summary: 'Edge-aligned modal surface.',
    attributes: [
      'open',
      'size',
      'label',
      'escape-key-action',
      'backdrop-action',
      'hide-close',
      'close-label',
      'placement',
    ],
    events: [
      { name: 'rg-before-close', type: 'CustomEvent<DialogBeforeCloseDetail>' },
      { name: 'rg-open-change', type: 'CustomEvent<DialogOpenChangeDetail>' },
      { name: 'rg-close', type: 'CustomEvent<DialogCloseDetail>' },
    ],
    slots: ['trigger', 'title', 'close', 'default', 'footer'],
    parts: ['trigger', 'base', 'dialog', 'panel', 'header', 'title', 'close', 'body', 'footer'],
  },
  {
    className: 'RgTooltipElement',
    tag: 'rg-tooltip',
    family: 'overlay',
    summary: 'Focus and hover supplementary label.',
    attributes: ['content', 'open', 'placement', 'delay', 'disabled'],
    events: [{ name: 'rg-open-change', type: 'CustomEvent<TooltipOpenChangeDetail>' }],
    slots: ['trigger', 'content'],
    parts: ['trigger', 'bubble', 'arrow'],
  },
  {
    className: 'RgButtonGroupElement',
    tag: 'rg-button-group',
    family: 'action',
    summary: 'Accessible horizontal or vertical action grouping.',
    attributes: ['attached', 'label', 'orientation'],
    slots: ['default'],
    parts: ['base', 'group'],
  },
  {
    className: 'RgComboboxElement',
    tag: 'rg-combobox',
    family: 'form',
    summary: 'Filterable, form-associated single-select combobox.',
    attributes: [
      'description',
      'disabled',
      'error',
      'filter',
      'invalid',
      'label',
      'name',
      'no-results-text',
      'open',
      'placeholder',
      'readonly',
      'required',
      'size',
      'value',
    ],
    events: [
      ...nativeValueEvents,
      { name: 'rg-open-change', type: 'CustomEvent<RgComboboxOpenChangeDetail>' },
      { name: 'rg-value-change', type: 'CustomEvent<RgComboboxValueChangeDetail>' },
    ],
    slots: ['label', 'description', 'error', 'default'],
    parts: [
      'field',
      'label-row',
      'label',
      'control-wrap',
      'control',
      'input',
      'toggle',
      'listbox',
      'empty',
      'description',
      'error',
    ],
  },
  {
    className: 'RgDatePickerElement',
    tag: 'rg-date-picker',
    family: 'form',
    summary: 'Form-associated date field backed by the native date picker.',
    attributes: [
      'description',
      'disabled',
      'error',
      'invalid',
      'label',
      'max',
      'min',
      'name',
      'readonly',
      'required',
      'size',
      'step',
      'value',
    ],
    events: nativeValueEvents,
    slots: ['label', 'description', 'error'],
    parts: [
      'field',
      'label-row',
      'label',
      'control-wrap',
      'control',
      'input',
      'icon',
      'description',
      'error',
    ],
  },
  {
    className: 'RgKbdElement',
    tag: 'rg-kbd',
    family: 'display',
    summary: 'Keyboard shortcut or physical key notation.',
    attributes: ['keys', 'label', 'separator'],
    slots: ['default'],
    parts: ['base'],
  },
  {
    className: 'RgFieldsetElement',
    tag: 'rg-fieldset',
    family: 'form',
    summary: 'Semantic grouping for related form controls.',
    attributes: ['description', 'disabled', 'error', 'invalid', 'legend'],
    slots: ['legend', 'description', 'default', 'error'],
    parts: ['base', 'fieldset', 'legend', 'description', 'content', 'error'],
  },
  {
    className: 'RgEmptyStateElement',
    tag: 'rg-empty-state',
    family: 'display',
    summary: 'Structured placeholder for an empty collection or workflow.',
    attributes: ['description', 'size', 'title', 'tone'],
    slots: ['icon', 'title', 'default', 'actions'],
    parts: ['base', 'icon', 'copy', 'title', 'description', 'actions'],
  },
  {
    className: 'RgBreadcrumbElement',
    tag: 'rg-breadcrumb',
    family: 'navigation',
    summary: 'Labeled hierarchy navigation trail.',
    attributes: ['label'],
    slots: ['default'],
    parts: ['base', 'nav', 'list'],
  },
  {
    className: 'RgBreadcrumbItemElement',
    tag: 'rg-breadcrumb-item',
    family: 'navigation',
    summary: 'Link or current location inside a breadcrumb trail.',
    attributes: ['current', 'href', 'target', 'rel'],
    slots: ['default'],
    parts: ['separator', 'base', 'link'],
  },
  {
    className: 'RgPaginationElement',
    tag: 'rg-pagination',
    family: 'navigation',
    summary: 'Compact paged navigation with configurable ranges.',
    attributes: [
      'boundary-count',
      'disabled',
      'label',
      'next-label',
      'page',
      'page-count',
      'previous-label',
      'sibling-count',
    ],
    events: [{ name: 'rg-page-change', type: 'CustomEvent<PaginationPageChangeDetail>' }],
    slots: [],
    parts: ['base', 'nav', 'button', 'previous', 'pages', 'next'],
  },
  {
    className: 'RgStepIndicatorElement',
    tag: 'rg-step-indicator',
    family: 'navigation',
    summary: 'Shows progress through a fixed, linear multi-step flow.',
    attributes: [
      'complete-label',
      'current-label',
      'label',
      'orientation',
      'upcoming-label',
      'value',
    ],
    slots: ['default'],
    parts: ['base', 'nav', 'list'],
  },
  {
    className: 'RgStepElement',
    tag: 'rg-step',
    family: 'navigation',
    summary: 'Names one stateful position inside a step indicator.',
    attributes: ['description', 'label', 'optional', 'optional-label', 'value'],
    slots: ['default', 'description'],
    parts: ['base', 'rail', 'line', 'marker', 'content', 'label', 'description', 'optional'],
  },
  {
    className: 'RgPopoverElement',
    tag: 'rg-popover',
    family: 'overlay',
    summary: 'Non-modal anchored content surface.',
    attributes: ['disabled', 'label', 'match-trigger-width', 'open', 'placement', 'trigger'],
    events: [{ name: 'rg-open-change', type: 'CustomEvent<RgPopoverOpenChangeDetail>' }],
    slots: ['trigger', 'default'],
    parts: ['trigger', 'panel', 'arrow'],
  },
  {
    className: 'RgMenuElement',
    tag: 'rg-menu',
    family: 'overlay',
    summary: 'Anchored action menu with roving keyboard focus.',
    attributes: ['disabled', 'label', 'open', 'placement'],
    events: [
      { name: 'rg-open-change', type: 'CustomEvent<RgMenuOpenChangeDetail>' },
      { name: 'rg-select', type: 'CustomEvent<RgMenuSelectDetail>' },
    ],
    slots: ['trigger', 'default'],
    parts: ['trigger', 'menu'],
  },
  {
    className: 'RgMenuItemElement',
    tag: 'rg-menu-item',
    family: 'overlay',
    summary: 'Selectable action owned by rg-menu.',
    attributes: ['disabled', 'value'],
    slots: ['start', 'default', 'end'],
    parts: ['base', 'item', 'start', 'label', 'end'],
  },
  {
    className: 'RgCopyButtonElement',
    tag: 'rg-copy-button',
    family: 'action',
    summary: 'Clipboard action with accessible success and error feedback.',
    attributes: [
      'copy-label',
      'disabled',
      'error-label',
      'feedback-duration',
      'from',
      'success-label',
      'value',
    ],
    events: [
      { name: 'rg-copy', type: 'CustomEvent<RgCopyDetail>' },
      { name: 'rg-error', type: 'CustomEvent<RgCopyErrorDetail>' },
    ],
    slots: ['copy-icon', 'success-icon', 'error-icon', 'default'],
    parts: ['base', 'button', 'icon', 'label', 'status'],
  },
  {
    className: 'RgChipGroupElement',
    tag: 'rg-chip-group',
    family: 'form',
    summary: 'Single or multiple selection group for interactive chips.',
    attributes: ['disabled', 'label', 'name', 'required', 'selection', 'value'],
    events: [
      ...nativeValueEvents,
      { name: 'rg-value-change', type: 'CustomEvent<RgChipValueChangeDetail>' },
    ],
    slots: ['default'],
    parts: ['base', 'label', 'group'],
  },
  {
    className: 'RgChipElement',
    tag: 'rg-chip',
    family: 'form',
    summary: 'Selectable or removable token owned by rg-chip-group.',
    attributes: [
      'aria-label',
      'aria-labelledby',
      'disabled',
      'removable',
      'remove-label',
      'selected',
      'size',
      'value',
    ],
    events: [{ name: 'rg-remove', type: 'CustomEvent<RgChipRemoveDetail>' }],
    slots: ['start', 'default', 'end'],
    parts: ['base', 'chip', 'start', 'label', 'end', 'remove'],
  },
  {
    className: 'RgSegmentedControlElement',
    tag: 'rg-segmented-control',
    family: 'form',
    summary: 'Form-associated exclusive view or mode selector.',
    attributes: [
      'disabled',
      'full-width',
      'label',
      'name',
      'orientation',
      'required',
      'size',
      'value',
    ],
    events: [
      ...nativeValueEvents,
      { name: 'rg-value-change', type: 'CustomEvent<RgSegmentedValueChangeDetail>' },
    ],
    slots: ['default'],
    parts: ['base', 'label', 'control', 'indicator'],
  },
  {
    className: 'RgSegmentElement',
    tag: 'rg-segment',
    family: 'form',
    summary: 'Exclusive option owned by rg-segmented-control.',
    attributes: ['disabled', 'selected', 'value'],
    slots: ['default'],
    parts: ['base', 'segment'],
  },
  {
    className: 'RgProgressRingElement',
    tag: 'rg-progress-ring',
    family: 'feedback',
    summary: 'Compact circular determinate or indeterminate progress indicator.',
    attributes: ['aria-label', 'label', 'max', 'show-value', 'size', 'value'],
    slots: [],
    parts: ['base', 'progress', 'visual', 'track', 'indicator', 'value'],
  },
  {
    className: 'RgRatingElement',
    tag: 'rg-rating',
    family: 'form',
    summary: 'Form-associated integer star rating input.',
    attributes: [
      'description',
      'disabled',
      'error',
      'invalid',
      'label',
      'max',
      'name',
      'readonly',
      'required',
      'size',
      'value',
    ],
    events: [
      ...nativeValueEvents,
      { name: 'rg-value-change', type: 'CustomEvent<RgRatingValueChangeDetail>' },
    ],
    slots: [],
    parts: ['field', 'label', 'control', 'description', 'error'],
  },
  {
    className: 'RgRelativeTimeElement',
    tag: 'rg-relative-time',
    family: 'display',
    summary: 'Localized relative date rendered with native Intl APIs.',
    attributes: ['date', 'format', 'lang', 'locale', 'numeric', 'sync'],
    slots: [],
    parts: ['base', 'time'],
  },
  {
    className: 'RgFormatDateElement',
    tag: 'rg-format-date',
    family: 'display',
    summary: 'Formats an absolute date and time with native Intl semantics.',
    attributes: [
      'date',
      'day',
      'era',
      'hour',
      'hour-format',
      'lang',
      'locale',
      'minute',
      'month',
      'second',
      'time-zone',
      'time-zone-name',
      'weekday',
      'year',
    ],
    slots: [],
    parts: ['base', 'time'],
  },
  {
    className: 'RgFormatNumberElement',
    tag: 'rg-format-number',
    family: 'display',
    summary: 'Formats decimal, percentage, and currency values for a locale.',
    attributes: [
      'currency',
      'currency-display',
      'lang',
      'locale',
      'maximum-fraction-digits',
      'maximum-significant-digits',
      'minimum-fraction-digits',
      'minimum-integer-digits',
      'minimum-significant-digits',
      'type',
      'value',
      'without-grouping',
    ],
    slots: [],
    parts: ['base', 'number'],
  },
  {
    className: 'RgFormatBytesElement',
    tag: 'rg-format-bytes',
    family: 'display',
    summary: 'Formats byte and bit quantities with decimal SI units.',
    attributes: ['display', 'lang', 'locale', 'unit', 'value'],
    slots: [],
    parts: ['base', 'value'],
  },
] as const satisfies readonly ComponentMetadata[];
